name: html_tags_cleaner
description: "A very simple and easy-to-use package to clean html tags from a string, simply by calling a method."
version: 0.0.3
homepage: https://github.com/Hery34/html_tags_cleaner.git

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:   
  uses-material-design: true

  assets:
    - assets/
  plugin:
    platforms:
        
      some_platform:
        pluginClass: somePluginClass

